config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web=>"/sidekiq"
  devise_for :users
  resources :blogs
  resources :users ,only: %w[show index destroy]
  post '/comment', to: 'blogs#create_comment'
  post '/delete_comment/:id', to: 'blogs#delete_comment'
  root to: 'blogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :comments
    belongs_to :user

    validates :title,presence: true
    validates :content,presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :blog
    validates :message,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
    has_many :blogs
    has_many :comments
    validates :name,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,only: %w(create_comment delete_comment new edit create update destroy)
  
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.order('created_at DESC')
  end
  
  def create_comment
    @comment=Comment.new(params.require(:comment).permit(:message,:blog_id,:user_id))
    if !@comment.save
      flash[:alert]="Comment empty!!"
    else
      if @comment.blog.user
        MailCommentJob.perform_later @comment.id
      end

    end

    redirect_to @comment.blog  
  end

  def delete_comment
    
    @comment = Comment.find(params[:id])

    if current_user.id != @comment.user_id
      redirect_to @blog
    end

    @blog=@comment.blog
    @comment.destroy
    redirect_to @blog
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @comments=Comment.where( blog_id: @blog.id).order('created_at DESC')

    @new_comment=Comment.new
    
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.user_id == current_user.id && @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.user_id == current_user.id && @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    if @blog.user_id == current_user.id
      @blog.destroy
      notice='Blog was successfully destroyed.'
    else
      notice='Not authorized to access this blog' 
    end
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: notice }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title,:content,:user_id)
    end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    def destroy
      current_user.invalidate_all_sessions!
      super
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    if !current_user.admin
      redirect_to blogs_path
    end
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

    @blogs=Blog.where(user:@user)
  end

  
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if !is_accessible @user
      return redirect_to root_path
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name,:email)
    end
end

=begin
  
# GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
=end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_accessible(user)
        return true if user_signed_in? && (current_user.admin||current_user.id==user.id)
        false
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
   
end

app/views/blogs/_form.html.erb
<%= form_for(blog,html:{class:"form-group"}) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%=f.label :title%>
    <%=f.text_field :title ,class:"form-control"%>
    </div>
     <div class="field">
    <%=f.label :content%>
    <%=f.text_area :content,class:"form-control"%>
    </div>
     
    <%= f.hidden_field :user_id, :value => current_user.id%>
    
<br>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<!---<p id="notice"><%= notice %></p>-->



<br>
   <div class="text-right">
  <%= link_to 'Create New Blog', new_blog_path,class:"btn btn-primary" %>
  </div>
  <br>

    <% @blogs.each do |blog| %>
    <div class="jumbotron">
      
        <h1><%= link_to blog.title, blog %></h1>
        
        <%if blog.user%>
        <span >
       by<i> <%=link_to blog.user.name,blog.user%></i><%=" "+blog.created_at.strftime('%B %d, %Y')%>
       </span>
       <%else%>
       <span>by<i> Annonymous</i> <%=" "+blog.created_at.strftime('%B %d, %Y')%>
      <%end%>
        <p><p>
        <%if user_signed_in? && current_user.id==blog.user_id%>
      <%= link_to 'Edit', edit_blog_path(blog), class:"btn btn-primary"%>
    <%= link_to 'Delete', blog,class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
    
      </div>
    <% end %>
 

<br>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<div class="jumbotron">
<h1 class="text-center">
    <%=@blog.title%>
</h1>
<hr class="my-4">
<p>
    
    <%=@blog.content%>
</p>
<p class=text-right>
 <%if @blog.user%>
  <i> by <%= link_to @blog.user.name,@blog.user%><%=" "+@blog.created_at.strftime('%B %d, %Y')%></i>
<%else%>
  <i> by Annonymous <%=" "+@blog.created_at.strftime('%B %d, %Y')%></i>
  <%end%>
</p>

<%if user_signed_in? && current_user.id==@blog.user_id%>
<%= link_to 'Edit', edit_blog_path(@blog),class:"btn btn-primary" %>|
<%end%>

<%= link_to 'Back', blogs_path ,class:"btn btn-primary"%>


</div>


<div >
<h1 class="container text-center">Comments</h1>


 <%= form_for @new_comment,url:"/comment", class:"form-group shadow-textarea" do |f| %>

    <div class="field">
    
    <%=f.text_area :message ,class:"form-control z-depth-1",rows:3 ,placeholder:"Write something here..."%>
    </div>
    <%= f.hidden_field :blog_id, :value => @blog.id %>
    <%= f.hidden_field :user_id, :value => current_user.id if user_signed_in?%>
    <br>
  <div class="actions text-right">
    <%= f.submit class:"btn btn-primary" %>
  </div>
  <br>
<% end %>

<!-- alert for comment empty-->
 <%if notice%>
  <p class="notice alert alert-danger"><%=flash[:alert] %></p>
  <%end%>


<ul class="list-group">
<% @comments.each do |comment| %>

<li class="list-group-item">
   
    
   <p><%if comment.user%><%=link_to comment.user.name,comment.user %>
   <%else%>Annonymous<%end%>
   <%="    "+ comment.created_at.strftime(' %H:%M , %B %d, %Y')%></p>
    <p><%=comment.message%> </p>
     <div class ="text-right">
    <%if user_signed_in? && (current_user.admin||current_user.id==comment.user_id)%>
    <%= link_to 'Delete', '/delete_comment/'+comment.id.to_s,class:"btn btn-danger", method: :post %>
    <%end%>
    </div>

</li>
<%end%>
</ul>
</div>
<%#=current_user.name%>
   

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <h1><%= link_to 'Blogs',root_path, class:"navbar-brand" %></h1>
    <form>
    <% if user_signed_in? %>
    <div style="padding-left: 10px;">
    Logged in as <strong><%= current_user.name %></strong>
    <%if current_user.admin %>
    <%= link_to 'Dashboard',users_path,class: 'btn btn-info'%>
    <%end%>

    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-dark' %> 
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-success'  %>
    <%else%>
    <div style="padding-left: 10px;">
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    </div>
    <% end %>
    </form>
</nav>


 
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <%=render 'layouts/navbar'%>
  <%if notice%>
  <p class="notice alert alert-danger"><%= notice %></p>
  <%end%>
  <%if alert%>
  <p class="alert alert-success"><%= alert %></p>
  <%end%>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

     <div class="field">
    <%=f.label :name%>
    <%=f.text_field :name%>
    </div>
     <div class="field">
    <%=f.label :email%>
    <%=f.text_field :email%>
    </div>
     

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_users_list.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Created At</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
     <% users.each do |user| %>
      <tr>
        
        <td><%=link_to user.name.capitalize(), user %></td>
        <td><%=user.created_at.strftime('%B %d, %Y')%></td>
        <td><%= link_to 'Delete', user,class:"btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
   
        
   
    <% end %>

  </tbody>
  </table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%#= notice %></p>

<h1>Users :<%=@users.length if @users%></h1>
<br>

<br>
<%= render partial: "users_list", locals: {users: @users} %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

   <div class=text-center>
   <h1> <%=@user.name.capitalize%></h1>
   </div>

<p>
    <strong>Email:</strong>
    <%=@user.email%>
    <%if user_signed_in? && (current_user.admin || @user.id==current_user.id)%>
<%= link_to 'Edit', edit_user_registration_path(@user),class:"btn btn-primary" %> |
<%= link_to 'Delete', @user,class:"btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>

</p>


<h1>Blogs : <%=@blogs.length if @blogs%></h1>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Created At</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
     <% @blogs.each do |blog| %>
      <tr>
        
        <td><%=link_to blog.title.capitalize(), blog %></td>
        <td><%=blog.created_at.strftime('%B %d, %Y')%></td>
        <%if user_signed_in? && (current_user.admin||current_user.id==blog.user_id)%>
        <td><%= link_to 'Edit', edit_blog_path(blog),class:"btn btn-primary" %></td>
        <td><%= link_to 'Delete', blog,class:"btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %></td>
       <%end%>
      </tr>
   
        
   
    <% end %>

  </tbody>
  </table>